"""
Zomato is planning to offer a premium membership to customers who have placed multiple orders in a single day.

Your task is to write a SQL query to find those customers who have placed multiple orders in a single day at least once. 
total order value generated by those customers and order value generated only by those orders, display the results in ascending order of total order value.

 

Table: orders (primary key : order_id)
+---------------+-------------+
| COLUMN_NAME   | DATA_TYPE   |
+---------------+-------------+
| customer_name | varchar(20) |
| order_date    | datetime    |
| order_id      | int         |
| order_value   | int         |
+---------------+-------------+
"""

with 
cte as (
select 
	  customer_name,
    cast(order_date as date) as order_date,
    count(*) as total_orders,
    sum(order_value) as total_values
from orders
group by customer_name, cast(order_date as date)
having count(*) > 1
),

  "- IN THE ABOVE CTE WE HAVE AGGREGATED THE DATA TOTAL ORDERS VALUES BASED ON CUSTOMER NAME & ORDER DATE THEN APPLIED ONE CONDITION IN HAVING FUNCTION WE WANT 
  TO CALCULATE THOSE CUSTOMERS TOTAL VALUE WHO ORDERED MORE THAN 2.
  -ALSO WE HAVE CASTING THE ORDER DATE FROM TIMESTAMP TO DATE COLUMN.
  "

cte1 as (
select 
	customer_name,
  	sum(total_values) as total_values
from cte
group by customer_name
),

"-IN ABOVE CTE1 WE HAVE AGGRAGATED THE TOTAL ORDERS VALUE BASED ON EACH CUSTOMERS FROM CTE TABLE"
  
cte2 as (
 select 
  	customer_name,
	sum(order_value) as total_ord_value
 FROM orders
 group by customer_name
)  

"- HERE IN ABOVE CTE2 WE HAVE CALCULATED AGGREGATED ORDER VALUE FOR EACH CUSTOMER, THERE IS NO CONDITION USED"
  
select 
	cte1.customer_name
    ,cte2.total_ord_value
    ,cte1.total_values
from cte1 left join cte2 
on cte1.customer_name = cte2.customer_name
order by total_ord_value ;

"- Here we have joined both cte1 & cte2 on customer name column. for required output view"






